// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCH570FEknEYDowGlugEyTovoeQRiL9xk',
    appId: '1:621336395690:web:37c024af2b6cf8267635d3',
    messagingSenderId: '621336395690',
    projectId: 'btolet-app',
    authDomain: 'btolet-app.firebaseapp.com',
    storageBucket: 'btolet-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHabG4Ogz-vZOnKCSJT1etFrb50jwWVWE',
    appId: '1:621336395690:android:cee3b4e41794b33f7635d3',
    messagingSenderId: '621336395690',
    projectId: 'btolet-app',
    storageBucket: 'btolet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt92ONr4zIX444ppbEqOqMW8ORz8HOphw',
    appId: '1:621336395690:ios:b47db53b08c8f0e77635d3',
    messagingSenderId: '621336395690',
    projectId: 'btolet-app',
    storageBucket: 'btolet-app.appspot.com',
    iosBundleId: 'com.example.btolet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt92ONr4zIX444ppbEqOqMW8ORz8HOphw',
    appId: '1:621336395690:ios:3ff01050106d90ab7635d3',
    messagingSenderId: '621336395690',
    projectId: 'btolet-app',
    storageBucket: 'btolet-app.appspot.com',
    iosBundleId: 'com.example.btolet.RunnerTests',
  );
}
